// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water.proto

package com.zeaho.proto.apple;

public interface AppleReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:apple.AppleReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
