// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apple.proto

package com.zeaho.proto.water;

public final class WaterProto {
  private WaterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_water_WaterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_water_WaterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_water_WaterReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_water_WaterReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013apple.proto\022\005water\"\035\n\014WaterRequest\022\r\n\005" +
      "price\030\001 \001(\002\"\035\n\nWaterReply\022\017\n\007message\030\001 \001" +
      "(\t2D\n\014WaterCompany\0224\n\010BuyWater\022\023.water.W" +
      "aterRequest\032\021.water.WaterReply\"\000B+\n\025com." +
      "zeaho.proto.waterB\nWaterProtoP\001\242\002\003HLWb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_water_WaterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_water_WaterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_water_WaterRequest_descriptor,
        new java.lang.String[] { "Price", });
    internal_static_water_WaterReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_water_WaterReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_water_WaterReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
