// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water.proto

package com.zeaho.proto.water;

public interface WaterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:water.WaterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float price = 1;</code>
   * @return The price.
   */
  float getPrice();
}
